TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.2
  min_obstacle_dist: 0.8

  acc_lim_theta: 2.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_z: 1.0

  holonomic_robot: false

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  sim_time: 2.0
  vx_samples: 12
  vtheta_samples: 30
  sim_granularity: 0.1
  angular_sim_granularity: 0.05

  meter_scoring: true
  # чуть больше «запас» чтобы он не застревал в «мёртвых зонах»
  oscillation_timeout: 10.0
  oscillation_distance: 0.5

  path_distance_bias: 40.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02

  in_place_rotation_allowed: true
  controller_frequency: 15.0
  planner_frequency: 5.0
  publish_cost_grid: true

  heading_lookahead: 0.4
  heading_scoring: true
  heading_scoring_timestep: 0.8
  dwa: true

  simple_attractor: false
  
  # Дополнительные параметры для дрона
  escape_vel: -0.2
  escape_reset_dist: 0.5
  escape_reset_theta: 0.5
  
  # Улучшенные параметры избегания препятствий
  gdist_scale: 1.0
  pdist_scale: 1.0
  alignment_required_dist: 0.5

