# basic_nav/config/recovery_behaviors.yaml

# Список recovery-behaviors загружается напрямую узлом move_base
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: aggressive_reset
    type: clear_costmap_recovery/ClearCostmapRecovery
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery

# Настройки подавления дрожания (oscillation)
oscillation_timeout: 10.0
oscillation_distance: 0.2

conservative_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_layer"]

aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_layer"]

rotate_recovery:
  sim_granularity: 0.017
  frequency: 20.0

# Настройки move_slow_and_clear оставлены для справки, но плагин не используется
# move_slow_and_clear:
#   clearing_distance: 0.5
#   limited_trans_speed: 0.1
#   limited_rot_speed: 0.4
#   limited_distance: 0.3
